on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Check source-code for project
        uses: actions/checkout@v1
      - name: Install Flutter and build the project
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.8'
      - name: Get all dependencies
        run: flutter pub get
      - name: Build apk release
        run: flutter build apk --release --split-per-abi
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
          releaseName: "Release ${{ github.run_number }}"
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: imap.gmail.com'
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Build successful
          body: 'The build was successful. Here is the built APK file as an attachment.'
          from: 'KARTHIK AVINASH IIIT Dharwad <21bcs052@iiitdwd.ac.in>'
          to: 'karthikavinash01@gmail.com'
          attachments: 'build/app/outputs/apk/release/*'
